import "./globals.css";
import axios from "axios";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "@/Context/userContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Providers } from "./providers";

import NavBar from "@/components/Nav";
import Footer from "@/components/Footer";
export default function RootLayout({ children }) {
  axios.defaults.withCredentials = true;

  return (
    <html lang="en" className="light">
      <body className="">
        <UserContextProvider>
          <Toaster position="bottom-right" toastOptions={{ duration: 2000 }} />
          <Providers>
            <NavBar />
            <main className="">{children} </main>
            <Footer />
          </Providers>
        </UserContextProvider>
      </body>
    </html>
  );
}
